language: node_js
node_js:
  - "node"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- npm install -g typescript
- npm install
- tsc
script:
- npm test